version: '3.8'

services:
  llm-service-nginx:
    image: nginx:latest
    container_name: llm-service-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      ai-network:
        ipv4_address: "170.20.0.10"

  llm-service-new-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-service-new-1
    environment:
      - SERVICE_NAME=llm-service-new
    env_file:
      - .env
    volumes:
      - ./logs-service-1:/app/logs
    networks:
      ai-network:
        ipv4_address: "170.20.0.11"

  llm-service-new-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-service-new-2
    environment:
      - SERVICE_NAME=llm-service-new
    env_file:
      - .env
    volumes:
      - ./logs-service-2:/app/logs
    networks:
      ai-network:
        ipv4_address: "170.20.0.12"

networks:
  ai-network:
    external:
      name: ai-network
