def general_prompt(main_brand, content):
    prompt = [{
        "role": "user",
        "content": "Trong ngữ cảnh xử lý dữ liệu lắng nghe mạng xã hội, hãy phân tích nội dung sau `{}` và xác định "
                   "các chỉ số sau. Kết quả trả về là một JSON theo cấu trúc chuẩn với các trường sau: \n\n- "
                   "**sentiment (Cảm xúc):** Đánh giá tổng quan sắc thái của nội dung, với các giá trị: NEGATIVE, "
                   "NEUTRAL, POSITIVE, MIXED.\n- **severity (Mức độ nghiêm trọng):** Đánh giá mức độ nghiêm trọng của "
                   "nội dung, với các trạng thái: LOW, MEDIUM, HIGH, VERY HIGH, CRITICAL.\n- **emotion (Cảm xúc):** "
                   "Cảm xúc được diễn đạt trong nội dung, với các giá trị: Anger (Cơn giận), Disgust (Sự ghê tởm), "
                   "Fear (Sự sợ hãi), Happiness (Hạnh phúc), Sadness (Nỗi buồn), Surprise (Sự ngạc nhiên), "
                   "Interest (Sự quan tâm), Joy (Niềm vui).\n- **polarity (Tính phân cực):** Chỉ số đo lường mức độ "
                   "cảm xúc của văn bản, được biểu diễn bằng giá trị thập phân trong khoảng từ -1 đến 1.\n- "
                   "**intensity (Cường độ):** Mức độ mạnh mẽ hoặc độ sâu của cảm xúc trong văn bản, với các giá trị: "
                   "LOW, MEDIUM, HIGH.\n- **topic (Chủ đề):** Chủ đề chính mà văn bản hoặc tài liệu tập trung vào.\n- "
                   "**subtopic (Chủ đề phụ):** Các chủ đề phụ là các lĩnh vực con của chủ đề chính, thường chi tiết "
                   "hơn.\n- **category (Danh mục):** Danh mục mà văn bản thuộc về.\n- **industry (Ngành công "
                   "nghiệp):** Lĩnh vực hoặc lĩnh vực kinh doanh cụ thể mà các tổ chức hoặc hoạt động thuộc về.\n- "
                   "**subject (Chủ đề):** Chủ đề hoặc vấn đề chính được đề cập trong văn bản, giúp xác định nội dung "
                   "chính và thường là yếu tố quan trọng trong phân loại và tìm kiếm thông tin.\n- **product_type ("
                   "Loại sản phẩm):** Phân loại hoặc nhóm các sản phẩm dựa trên đặc điểm hoặc thuộc tính của chúng, "
                   "giúp quản lý, phân tích, và tìm kiếm dễ dàng hơn.\n- **angle (Quan điểm):** Quan điểm được đề cập "
                   "trong văn bản.\n- **intent (Ý định):** Mục tiêu hoặc mục đích của hành động hoặc yêu cầu trong "
                   "văn bản, giúp hiểu rõ hơn về mong muốn hoặc nhu cầu của người dùng.\n- **purpose (Mục đích):** Lý "
                   "do hoặc mục tiêu mà người dùng hoặc tác giả hướng tới khi tạo ra một đoạn văn bản hoặc yêu "
                   "cầu.\n- **tone (Tông cảm xúc):** Tông cảm xúc chính được thể hiện trong văn bản, bao gồm các giá "
                   "trị: Friendly (Thân thiện), Informal (Không chính thức), Positive (Tích cực), Excited (Hứng "
                   "thú).\n- **audience (Đối tượng):** Đối tượng được nhắc đến trong văn bản. Nếu không có, "
                   "để trống.\n- **mention_mainbrand (Đề cập đến thương hiệu chính):** True nếu thương hiệu chính tồn "
                   "tại trong văn bản, False nếu không có.\n- **context (Bối cảnh):** Danh sách các đối tượng gòm các "
                   "từ khóa liên quan đến cảm xúc của văn bản:\n  - **sentiment (Cảm xúc):** Cảm xúc của từ khóa: "
                   "NEGATIVE, POSITIVE.\n  - **value (Giá trị):** từ khóa (yêu cầu từ khóa ngắn gọn) thể hiện cảm "
                   "xúc.\n- **explanation (Giải thích):** Tóm tắt ngắn gọn hoặc mô tả về nội dung chính trong văn "
                   "bản.\n- **spam (Rác rưởi):** Xác định xem văn bản có phải là spam hay không, với kết quả là chuỗi "
                   "'YES' hoặc 'NO'.\n- **advertisement (Quảng cáo):** Xác định xem văn bản có phải là quảng cáo sản "
                   "phẩm hoặc dịch vụ hay không, với kết quả là chuỗi 'YES' hoặc 'NO'.\n- **opinion_expressed (Ý kiến "
                   "được thể hiện):** Xác định xem văn bản có chứa ý kiến hay không, với kết quả là chuỗi 'YES' hoặc "
                   "'NO'.\n- **emotional_tone (Tông màu cảm xúc):** Xác định xem văn bản có chứa tông màu cảm xúc hay "
                   "không, với kết quả là chuỗi 'YES' hoặc 'NO'.\n- **feedback_provided (Phản hồi được cung cấp):** "
                   "Xác định xem văn bản có cung cấp phản hồi hay không, với kết quả là chuỗi 'YES' hoặc 'NO'.\n- "
                   "**insight_provided (Nhận thức được cung cấp):** Xác định xem văn bản có cung cấp nhận thức hay "
                   "không, với kết quả là chuỗi 'YES' hoặc 'NO'.\n\nKết quả trả về là một json theo format và dữ liệu "
                   "như sau: \n\n{\n    \"sentiment\": \"NEGATIVE\",          // kiểu dữ liệu: string, luôn có giá "
                   "trị, có thể là \"NEGATIVE\", \"NEUTRAL\", \"POSITIVE\", \"MIXED\".\n    \"severity\": null,       "
                   "         // kiểu dữ liệu: string, có thể là \"LOW\", \"MEDIUM\", \"HIGH\", \"VERY HIGH\", "
                   "\"CRITICAL\", hoặc null nếu không tìm thấy giá trị.\n    \"emotion\": null,                 "
                   "// kiểu dữ liệu: string, có thể là \"Anger\", \"Disgust\", \"Fear\", \"Happiness\", \"Sadness\", "
                   "\"Surprise\", \"Interest\", \"Joy\", hoặc null nếu không tìm thấy giá trị.\n    \"polarity\": "
                   "null,                // kiểu dữ liệu: number, thập phân từ -1 đến 1, hoặc null nếu không tìm thấy "
                   "giá trị.\n    \"intensity\": null,               // kiểu dữ liệu: string, có thể là \"LOW\", "
                   "\"MEDIUM\", \"HIGH\", hoặc null nếu không tìm thấy giá trị.\n    \"topic\": null,                 "
                   "  // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá trị.\n    \"subtopic\": null,         "
                   "       // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá trị.\n    \"category\": null,    "
                   "            // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá trị.\n    \"industry\": "
                   "null,                // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá trị.\n    "
                   "\"subject\": null,                 // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá "
                   "trị.\n    \"product_type\": null,            // kiểu dữ liệu: string, hoặc null nếu không tìm "
                   "thấy giá trị.\n    \"angle\": null,                   // kiểu dữ liệu: string, hoặc null nếu "
                   "không tìm thấy giá trị.\n    \"intent\": null,                  // kiểu dữ liệu: string, "
                   "hoặc null nếu không tìm thấy giá trị.\n    \"purpose\": null,                 // kiểu dữ liệu: "
                   "string, hoặc null nếu không tìm thấy giá trị.\n    \"tone\": null,                    // kiểu dữ "
                   "liệu: string, có thể là \"Friendly\", \"Informal\", \"Positive\", \"Excited\", hoặc null nếu "
                   "không tìm thấy giá trị.\n    \"audience\": null,                // kiểu dữ liệu: string, "
                   "hoặc null nếu không tìm thấy giá trị.\n    \"mention_mainbrand\": null,       // kiểu dữ liệu: "
                   "boolean, hoặc null nếu không tìm thấy giá trị.\n    \"context\": [                     // kiểu dữ "
                   "liệu: danh sách các đối tượng, mỗi đối tượng là một object chứa:\n        {\n            "
                   "\"sentiment\": null,      // kiểu dữ liệu: string, có thể là \"NEGATIVE\", \"NEUTRAL\", "
                   "\"POSITIVE\", \"MIXED\", hoặc null nếu không tìm thấy giá trị.\n            \"value\": null       "
                   "    // kiểu dữ liệu: string, hoặc null nếu không tìm thấy giá trị.\n        }\n    ],"
                   "\n    \"explanation\": null,             // kiểu dữ liệu: string, hoặc null nếu không tìm thấy "
                   "giá trị.\n    \"spam\": null,                    // kiểu dữ liệu: string, có thể là \"YES\" hoặc "
                   "\"NO\", hoặc null nếu không tìm thấy giá trị.\n    \"advertisement\": null,           // kiểu dữ "
                   "liệu: string, có thể là \"YES\" hoặc \"NO\", hoặc null nếu không tìm thấy giá trị.\n    "
                   "\"opinion_expressed\": null,       // kiểu dữ liệu: string, có thể là \"YES\" hoặc \"NO\", "
                   "hoặc null nếu không tìm thấy giá trị.\n    \"emotional_tone\": null,          // kiểu dữ liệu: "
                   "string, có thể là \"YES\" hoặc \"NO\", hoặc null nếu không tìm thấy giá trị.\n    "
                   "\"feedback_provided\": null,       // kiểu dữ liệu: string, có thể là \"YES\" hoặc \"NO\", "
                   "hoặc null nếu không tìm thấy giá trị.\n    \"insight_provided\": null         // kiểu dữ liệu: "
                   "string, có thể là \"YES\" hoặc \"NO\", hoặc null nếu không tìm thấy giá trị.\n}"
    },
        {
            "role": "user",
            "content": "Đây là prompt để thực hiện xử lý văn bản trong xử lý ngôn ngữ tự nhiên về dữ liệu lắng nghe "
                       "mạng xã hội, hãy xử lý dữ liệu sau:"
        },
        {
            "role": "user",
            "content": "Đây là prompt để thực hiện xử lý văn bản trong xử lý ngôn ngữ tự nhiên về dữ liệu lắng nghe "
                       "mạng xã hội, hãy xử lý dữ liệu sau:"
        },
        {
            "role": "user",
            "content": f"content: \"{content}\"\nmain_brand: [\"{main_brand}\"]"
        },
        {
            "role": "user",
            "content": "Please ensure the following fields are present in the JSON response. If any field is missing, "
                       "re-run the prompt until all fields are present:\n\n- \"sentiment\",\n- \"severity\","
                       "\n- \"emotion\",\n- \"polarity\",\n- \"intensity\",\n- \"topic\",\n- \"subtopic\","
                       "\n- \"category\",\n- \"industry\",\n- \"subject\",\n- \"product_type\",\n- \"angle\","
                       "\n- \"intent\",\n- \"purpose\",\n- \"tone\",\n- \"audience\",\n- \"mention_mainbrand\","
                       "\n- \"context\",\n- \"explanation\",\n- \"spam\",\n- \"advertisement\","
                       "\n- \"opinion_expressed\",\n- \"emotional_tone\",\n- \"feedback_provided\","
                       "\n- \"insight_provided\".\n\nMake sure that all these fields are present in the JSON response."
        }

    ]
    return prompt
